# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 18:27
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('IN', 'Individual'), ('CO', 'Company')], max_length=2)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('website', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('pinterest', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('standard_video', models.CharField(blank=True, max_length=255)),
                ('vr_video', models.CharField(blank=True, max_length=255)),
                ('recommend_count', models.IntegerField(default=0)),
                ('indifferent_count', models.IntegerField(default=0)),
                ('donotrecommend_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
