# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170413_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='donotrecommend_count',
            new_name='donotrecommend',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='indifferent_count',
            new_name='indifferent',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='recommend_count',
            new_name='recommends',
        ),
    ]
