# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170413_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recommends',
        ),
        migrations.AddField(
            model_name='profile',
            name='recommend',
            field=models.ManyToManyField(blank=True, related_name='recommends', to='profiles.Profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='donotrecommend',
        ),
        migrations.AddField(
            model_name='profile',
            name='donotrecommend',
            field=models.ManyToManyField(blank=True, related_name='does_not_recommend', to='profiles.Profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='indifferent',
        ),
        migrations.AddField(
            model_name='profile',
            name='indifferent',
            field=models.ManyToManyField(blank=True, related_name='is_indifferent', to='profiles.Profile'),
        ),
    ]
