# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 17:25
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170413_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='profile_image'),
        ),
    ]
